name: plonk book

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-katex
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-katex

      - name: Build plonk book
        run: mdbook build plonk-book/

      - name: Make release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
          # mark as prerelease if not main branch
          prerelease: ${{ github.ref_name != 'main' }}
          title: ${{ github.ref_name == 'main' && 'PDF' || github.ref_name }}
          files: ./plonk-book/book/*.pdf
